# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Intel Pin
        run: wget https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.17-98314-g0c048d619-gcc-linux.tar.gz -O ~/pin.tar.gz
      
      - name: Extract Intel Pin
        run: tar zxvf ~/pin.tar.gz
       
      - name: Set ENV
        run: echo "PIN_ROOT=~/pin" >> $GITHUB_PATH

      - name: Set Path
        run: echo "$GITHUB_ENV=$GITHUB_ENV:$PIN_ROOT" >> $GITHUB_ENV

      - name: Build
        working-directory: coverage/pin
        run: make 
          
      # This should fail for now...  
      - name: Run test
        run: pin -t obj-intel64/CodeCoverage.so -- testcase/boombox.exe
